config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Succesffully created new Pin!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was succesfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classpin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% flash.each do |name, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pins/_form.html.erb
<% if @pin.errors.any? %>
  <ul><% @pin.errors.full_messages.each do |error_msg| %>
    <li>
      <%= error_msg %>
    </li>
  <% end %></ul>
<% end %>

<%= form_for @pin do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.submit "Pin It!", class: "btn btn-primary"%>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>

<%= render 'form' %>

<%= link_to "Cancel", pin_path %>

app/views/pins/index.html.erb
<h1><%= link_to "Create New Pin", new_pin_path %></h1>
<% @pins.each do |pin| %>
  <div class="container">
    <%= link_to pin.title, pin %>
  </div>
<% end %>

app/views/pins/new.html.erb
<div class="container">
  <h1>New Pin</h1>

  <%= render 'form' %>

  <%= link_to "Back", root_path %>
</div>

app/views/pins/show.html.erb
<div class="container">
  <h1><%= @pin.title %></h1><br>
  <p><%= @pin.description %></p>

  <p>Submitted by <%= @pin.user.email %><br>
  <%= link_to "Home", root_path %>
  <%= link_to "Edit", edit_pin_path %>
  <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure you want to delete this pin?"} %></p>

</div>